// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Abonament {
	public Abonament(int pret, String denumire, Sala sala, ClaseFitness clasefitness,
	AntrenamentInstructor antrenamentinstructor) {
		this.pret = pret;
		this.denumire = denumire;
		this.sala = sala;
		this.clasefitness = clasefitness;
		this.antrenamentinstructor = antrenamentinstructor;
	}
	/**
	 * 
	 */
	public int pret;
	/**
	 * 
	 */
	public String denumire;
	/**
	 * 
	 */
	public Sala sala;
	/**
	 * 
	 */
	public ClaseFitness clasefitness;
	/**
	 * 
	 */
	public AntrenamentInstructor antrenamentinstructor;

	/**
	 * 
	 */
	public void afisareAbonament() {
		System.out.println("Pret: " + pret + " Denumire: " + denumire);
	}

	/**
	 * 
	 */
	public void modificarePret(int pret) {
		this.pret = pret;
	}

	/**
	 * 
	 */
	public void modificareDenumire(String denumire) {
		this.denumire = denumire;
	}
}
