// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Abonament {
	/**
	 * 
	 */
	public int pret;
	/**
	 * 
	 */
	public String denumire;
	/**
	 * 
	 */
	public Sala sala;
	/**
	 * 
	 */
	public ClaseFitness clasefitness;
	/**
	 * 
	 */
	public AntrenamentInstructor antrenamentinstructor;

	/**
	 * 
	 */
	public void afisareAbonament() {
	}

	/**
	 * 
	 */
	public void modificarePret() {
	}

	/**
	 * 
	 */
	public void modificareDenumire() {
	}
}
