// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class AntrenamentInstructor {
	public AntrenamentInstructor(String nume, int durata) {
		this.nume = nume;
		this.durata = durata;
	}
	/**
	 * 
	 */
	public String nume;
	/**
	 * 
	 */
	public int durata;
	/**
	 * 
	 */
	public void afisareAntrenamentInstructor() {
	}

	/**
	 * 
	 */
	public void modificareAntrenamentInstructor() {
	}
}
