// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class AntrenamentInstructor {
	/**
	 * 
	 */
	public String nume;
	/**
	 * 
	 */
	public int durata;

	/**
	 * 
	 */
	public void afisareAntrenamentInstructor() {
	}

	/**
	 * 
	 */
	public void modificareAntrenamentInstructor() {
	}
}
