// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class ClaseFitness {
	public ClaseFitness(String denumire, int durata, String ziSaptamana, int oraIncepere) {
		this.denumire = denumire;
		this.durata = durata;
		this.ziSaptamana = ziSaptamana;
		this.oraIncepere = oraIncepere;
	}
	/**
	 * 
	 */
	public String denumire;
	/**
	 * 
	 */
	public int durata;
	/**
	 * 
	 */
	public String ziSaptamana;
	/**
	 * 
	 */
	public int oraIncepere;

	/**
	 * 
	 */
	public void afisareClasaFitness() {
	}

	/**
	 * 
	 */
	public void modificareClasaFitness() {
	}
}
