// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class ClaseFitness {
	/**
	 * 
	 */
	public String denumire;
	/**
	 * 
	 */
	public int durata;
	/**
	 * 
	 */
	public String ziSaptamana;
	/**
	 * 
	 */
	public int oraIncepere;

	/**
	 * 
	 */
	public void afisareClasaFitness() {
	}

	/**
	 * 
	 */
	public void modificareClasaFitness() {
	}
}
