// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Client extends Persoana {
	/**
	 * 
	 */
	public Abonament[] abonament;
	/**
	 * 
	 */
	public Factura[] factura;

	/**
	 * 
	 */
	public void afisareAbonamente() {
	}

	/**
	 * 
	 */
	public void plataAbonament() {
	}

	/**
	 * 
	 */
	public void creeareAbonament() {
	}

	/**
	 * 
	 */
	public void anulareAbonament() {
	}

	/**
	 * 
	 */
	public void afisareFactura() {
	}

	/**
	 * 
	 */
	public void platireFactura() {
	}
}
