// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Client extends Persoana {
	public Client(String dataNastere, String email, String cNP, String prenume, String nume, int fonduri) {
		super(dataNastere, email, cNP, prenume, nume);
		this.fonduri = fonduri;
	}

	/**
	 * 
	 */
	public Abonament abonament;
	/**
	 * 
	 */
	public Factura factura;
	
	public ModalitatePlata modalitatePlata;
	public int fonduri;

	/**
	 * 
	 */
	public void afisareAbonament() {
		if(abonament != null)
		{
			System.out.println("Denumire abonament: " + abonament.denumire + "Pret abonament: " + abonament.pret);
			return;
		}
		System.out.println("Nu exista abonament!");
	}

	public void adaugareFactura(Factura factura)
	{
		this.factura = factura;
		System.out.println("Factura a fost adaugata cu succes!");
	}
	/**
	 * 
	 */
	public void plataAbonament() {
		System.out.println("Abonamentul a fost platit cu succes!");
	}

	/**
	 * 
	 */
	public void creeareAbonament( Abonament abonament) {
		this.abonament = abonament;
		System.out.println("Abonamentul a fost creat cu succes!");
	}
	/**
	 * 
	 */
	public void afisareFactura() {
		if(factura!= null)
		{
			System.out.println(factura.data);
			System.out.println(factura.suma);
			return;
		}
		System.out.println("Nu exista factura!");
	}

	/**
	 * 
	 */
	public void platireFactura() {
		if(factura == null)
		{
			System.out.println("Nu exista factura!");
		}
		System.out.println("Factura a fost platita cu succes!");
	}

	public boolean solicitareAbonamentNou(String denumireAbonamentAles){
		afisareAbonamente();
		if(this.abonament == null){
			System.out.println("Aveti deja un abonament!");
			return false;
		}
		return true;
	}

	private void afisareAbonamente(){
		for(Abonament a : MainProject.abonamente){
			System.out.println("Denumire : " + a.denumire + "Pret: " + a.pret);
		}
	}
	
	public boolean introducereMetodaPlata(String metodaPlata) {
		if(metodaPlata.equals("CASH")){
			modalitatePlata = ModalitatePlata.CASH;
			return true;
		} else if(metodaPlata.equals("CARD")){
			modalitatePlata = ModalitatePlata.CARD;
			return true;
		}
		return false;
	}
	
	public boolean adaugareAbonament(String denumireAbonament) {
		Abonament abonament = new Abonament(0,"",null,null,null);
		for(Abonament a : MainProject.abonamente) {
			if(denumireAbonament.equals(a.denumire)) {
				abonament.denumire = a.denumire;
				abonament.pret = a.pret;
			}
		}
		
		if(abonament == null)
			return false;
		
		if(abonament.pret > fonduri)
			return false;
		
		this.abonament = abonament;
		return true;
	}
}
