// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Factura {	
	public Factura(int suma, String data, ModalitatePlata modalitatePlata, Client client) {
		this.suma = suma;
		this.data = data;
		this.modalitatePlata = modalitatePlata;
		this.client = client;
	}
	/**
	 * 
	 */
	public int suma;
	/**
	 * 
	 */
	public String data;
	/**
	 * 
	 */
	public ModalitatePlata modalitatePlata;


	/**
	 * 
	 */
	public Client client;

	/**
	 * 
	 */
	public void afisareFactura() {
		System.out.println("Suma: " + suma + " Data: " + data + " Modalitate plata: " + modalitatePlata);
	}

	/**
	 * 
	 */
	public void modificareFactura(int suma, String data, ModalitatePlata modalitatePlata) {
		this.suma = suma;
		this.data = data;
		this.modalitatePlata = modalitatePlata;
	}
}
