// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Factura {
	/**
	 * 
	 */
	public int suma;
	/**
	 * 
	 */
	public String data;
	/**
	 * 
	 */
	public ModalitatePlata modalitatePlata;
	/**
	 * 
	 */
	public Client client;

	/**
	 * 
	 */
	public void afisareFactura() {
	}

	/**
	 * 
	 */
	public void modificareFactura() {
	}
}
