// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Manager extends Persoana {
	/**
	 * 
	 */
	public void blackListClient() {
	}

	/**
	 * 
	 */
	public void afisareClienti() {
	}

	/**
	 * 
	 */
	public void afisareAbonamente() {
	}

	/**
	 * 
	 */
	public void afisareSali() {
	}

	/**
	 * 
	 */
	public void afisareFacturi() {
	}

	/**
	 * 
	 */
	public void modificareAbonament() {
	}

	/**
	 * 
	 */
	public void adaugareSala() {
	}

	/**
	 * 
	 */
	public void modificareSala() {
	}

	/**
	 * 
	 */
	public void stergeSala() {
	}
}
