// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Manager extends Persoana {
	public Manager(String dataNastere, String email, String cNP, String prenume, String nume) {
		super(dataNastere, email, cNP, prenume, nume);
	}
	/**
	 * 
	 */

	/**
	 * 
	 */
	public void afisareClienti(Client[] clienti) {
		for(int i = 0; i < clienti.length; i++)
		{
			System.out.println("Clientul " + (i+1) + ":");
			clienti[i].afisarePersoana();
		}
	}

	/**
	 * 
	 */				
	public void afisareAbonamente(Abonament[] abonamente) {
		for(int i =0; i< abonamente.length; i++)
		{
			System.out.println("Abonamentul " + (i+1) + ":");
			abonamente[i].afisareAbonament();
		}
	}

	/**
	 * 
	 */
	public void afisareSali(Sala[] sali) {
		for(int i = 0; i < sali.length; i++)
		{
			System.out.println("Sala " + (i+1) + ":");
			sali[i].afisareSala();
		}
	}

	/**
	 * 
	 */
	public void afisareFacturi(Factura[] facturi) {
		for(int i = 0; i < facturi.length; i++)
		{
			System.out.println("Factura " + (i+1) + ":");
			facturi[i].afisareFactura();
		}
	}
}
