// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Persoana {
	/**
	 * 
	 */
	public String dataNastere;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String CNP;
	/**
	 * 
	 */
	public String prenume;
	/**
	 * 
	 */
	public String nume;

	/**
	 * 
	 */
	public void afisarePersoana() {
	}

	/**
	 * 
	 */
	public void modificarePersoana() {
	}
}
