// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

import java.io.Console;
import java.util.concurrent.ConcurrentHashMap;

/************************************************************/
/**
 * 
 */
public class Persoana {
	
	public Persoana(String dataNastere, String email, String cNP, String prenume, String nume) {
		this.dataNastere = dataNastere;
		this.email = email;
		CNP = cNP;
		this.prenume = prenume;
		this.nume = nume;
	}
	/**
	 * 
	 */
	public String dataNastere;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String CNP;
	/**
	 * 
	 */
	public String prenume;
	/**
	 * 
	 */
	public String nume;

	/**
	 * 
	 */
	public void afisarePersoana() {
		System.out.println("Nume: " + nume + " Prenume: " + prenume + " Data nastere: " + dataNastere + " Email: "
				+ email + " CNP: " + CNP);
	}
	/**
	 * 
	 */
	public void modificarePersoana(String dataNastere, String email, String cNP, String prenume, String nume) {
		this.dataNastere = dataNastere;
		this.email = email;
		CNP = cNP;
		this.prenume = prenume;
		this.nume = nume;
	}
}
