// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Sala {
	public Sala(String nume, String adresa) {
		this.nume = nume;
		this.adresa = adresa;
	}
	/**
	 * 
	 */
	public String nume;
	/**
	 * 
	 */
	public String adresa;
	/**
	 * 
	 */
	public void afisareSala() {
		System.out.println("Nume: " + nume + " Adresa: " + adresa);
	}
	/**
	 * 
	 */
	public void modificareSala(String nume, String adresa) {
		this.nume = nume;
		this.adresa = adresa;
	}
}
