// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaClaseIsp;

/************************************************************/
/**
 * 
 */
public class Sala {
	/**
	 * 
	 */
	public String nume;
	/**
	 * 
	 */
	public String adresa;

	/**
	 * 
	 */
	public void afisareSala() {
	}

	/**
	 * 
	 */
	public void modificareSala() {
	}
}
